/** Brand logos sourced from Auto.ru URLs in the supplied HAR and stored locally. */
export const catalogBrandLogos: Record<string, string | readonly string[]> = {
  "Aston Martin": "/assets/brand-logos/aston-martin.png",
  Audi: "/assets/brand-logos/audi.png",
  Bentley: "/assets/brand-logos/bentley.png",
  BMW: "/assets/brand-logos/bmw.png",
  Cadillac: "/assets/brand-logos/cadillac.png",
  Chevrolet: "/assets/brand-logos/chevrolet.png",
  Citroen: "/assets/brand-logos/citroen.png",
  Citroën: "/assets/brand-logos/citroen.png",
  "Citroen-DS": "/assets/brand-logos/ds.png",
  "Citroen-ds": "/assets/brand-logos/ds.png",
  DS: "/assets/brand-logos/ds.png",
  "DS Automobiles": "/assets/brand-logos/ds.png",
  Dodge: "/assets/brand-logos/dodge.png",
  Ferrari: "/assets/brand-logos/ferrari.png",
  Ford: "/assets/brand-logos/ford.png",
  Genesis: "/assets/brand-logos/genesis.png",
  GMC: "/assets/brand-logos/gmc.png",
  Honda: "/assets/brand-logos/honda.png",
  Hummer: "/assets/brand-logos/hummer.png",
  Hyundai: "/assets/brand-logos/hyundai.png",
  Jaguar: "/assets/brand-logos/jaguar.png",
  Jeep: "/assets/brand-logos/jeep.png",
  KGM: "/assets/brand-logos/kgm.png",
  KG_Mobility_Ssangyong: "/assets/brand-logos/kgm.png",
  Kia: "/assets/brand-logos/kia.png",
  "Land Rover": "/assets/brand-logos/land-rover.png",
  Lexus: "/assets/brand-logos/lexus.png",
  Lincoln: "/assets/brand-logos/lincoln.png",
  Lotus: "/assets/brand-logos/lotus.png",
  Maserati: "/assets/brand-logos/maserati.png",
  "Mercedes-Benz": "/assets/brand-logos/mercedes-benz.png",
  MINI: "/assets/brand-logos/mini.png",
  Mini: "/assets/brand-logos/mini.png",
  Peugeot: "/assets/brand-logos/peugeot.png",
  Porsche: "/assets/brand-logos/porsche.png",
  "Renault Korea": "/assets/brand-logos/renault.png",
  Renault: "/assets/brand-logos/renault.png",
  Smart: "/assets/brand-logos/smart.png",
  Suzuki: "/assets/brand-logos/suzuki.png",
  Toyota: "/assets/brand-logos/toyota.png",
  Volkswagen: "/assets/brand-logos/volkswagen.png",
  Volvo: "/assets/brand-logos/volvo.png",
};
