import { Client } from "pg";
import { config } from "dotenv";
import { calculateRuVladivostok, CALC_VERSION } from "../src/server/calc/ru";
import { getCbrCalcRates } from "../src/server/calc/rates";
config({ path: ".env.local", quiet: true }); config({ path: ".env", quiet: true });
const dbUrl=process.env.SUPABASE_DB_URL; if(!dbUrl) throw new Error("SUPABASE_DB_URL is required");
const chunk=<T,>(a:T[],n:number)=>Array.from({length:Math.ceil(a.length/n)},(_,i)=>a.slice(i*n,i*n+n));
async function main(){const c=new Client({connectionString:dbUrl,ssl:{rejectUnauthorized:false}});await c.connect();try{const rates=await getCbrCalcRates();const q=await c.query(`select c.id,c.primary_source,c.source_id,c.brand,c.model,c.year,c.registration_month,c.price_krw,c.engine_cc,c.power_hp,c.fuel_type from public.cars c where c.primary_source='chestny_prigon' and c.is_available and not exists(select 1 from public.calc_snapshots s where s.car_id=c.id and s.calc_version=$1)`,[CALC_VERSION]);const rows=q.rows.map(car=>({car,calc:calculateRuVladivostok({priceKrw:Number(car.price_krw),year:Number(car.year),month:car.registration_month??6,engineCc:Number(car.engine_cc),powerHp:Number(car.power_hp),fuelType:car.fuel_type,rates:rates.rates,customsRates:rates.customsRates,ratesAsOf:rates.asOf,ratesSource:rates.source,rateDetails:rates.rateDetails})}));for(const part of chunk(rows,100)){const values:any[]=[];const tuples=part.map(({car,calc})=>{const input={...car,resolvedPowerHp:car.power_hp};const rs={...calc.rates,asOf:calc.ratesAsOf,source:calc.ratesSource,details:calc.rateDetails};const fields=[car.id,calc.calcVersion,input,rs,calc,Math.round(calc.carPriceRub),Math.round(calc.dutyRub),Math.round(calc.feesRub),Math.round(calc.utilRub),Math.round(calc.freightRub),Math.round(calc.brokerRub),Math.round(calc.totalRub)];const marks=fields.map(x=>{values.push(x);return '$'+values.length});return '('+marks.join(',')+')'});await c.query(`insert into public.calc_snapshots(car_id,calc_version,inputs,rates,result,car_price_rub,duty_rub,fees_rub,util_rub,freight_rub,broker_rub,total_rub) values ${tuples.join(',')}`,values);const ids=part.map(x=>x.car.id),prices=part.map(x=>Math.round(x.calc.totalRub));await c.query(`update public.cars as c set price_rub=v.price from unnest($1::uuid[],$2::bigint[]) as v(id,price) where c.id=v.id`,[ids,prices]);}console.log(JSON.stringify({recalculated:rows.length,rateDate:rates.asOf,calcVersion:CALC_VERSION},null,2));}finally{await c.end()}}
main().catch(e=>{console.error(e);process.exit(1)});
