import { config } from "dotenv";
import { createClient } from "@supabase/supabase-js";
import { fetch, ProxyAgent } from "undici";
import { readFile } from "node:fs/promises";
import { ENCAR_HEADERS } from "../src/server/imports/encar-client";

config({ path: ".env", quiet: true });
/* eslint-disable @typescript-eslint/no-explicit-any -- the Supabase client generic is required for the untyped worker queue */
const url = process.env.NEXT_PUBLIC_SUPABASE_URL?.trim(); const key = (process.env.SUPABASE_SECRET_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY)?.trim(); const proxy = process.env.ENCAR_PROXY_URL?.trim();
const batch = Math.min(50, Math.max(1, Number(process.env.ENCAR_UNIVERSAL_BATCH_SIZE ?? 50))); const delay = Math.max(1000, Number(process.env.ENCAR_UNIVERSAL_DELAY_MS ?? 3000));
if (!url || !key || !proxy) throw new Error("Supabase credentials and ENCAR_PROXY_URL are required");
type Row = { id: string; source: string; source_listing_id: string; task: Record<string, boolean>; candidate_snapshot: Record<string, unknown> }; type Probe = { status: number; body?: unknown; error?: string };
const db = createClient<any>(url, key, { auth: { persistSession: false, autoRefreshToken: false } }); const agent = new ProxyAgent(proxy); const sleep = (n: number) => new Promise((r) => setTimeout(r, n));
const idOf = (r: Row) => String(r.candidate_snapshot.encarId ?? r.source_listing_id);
async function get(endpoint: string): Promise<Probe> { try { const r = await fetch(endpoint, { headers: ENCAR_HEADERS, dispatcher: agent, signal: AbortSignal.timeout(20000) }); return r.ok ? { status: r.status, body: await r.json() } : { status: r.status }; } catch (e) { return { status: 0, error: e instanceof Error ? e.message : String(e) }; } }
function classification(p: Probe) { if (p.status >= 200 && p.status < 300) return "ready"; if (/captcha/i.test(p.error ?? "")) return "captcha"; if (/timeout|abort/i.test(p.error ?? "")) return "timeout"; if (/proxy|socket|fetch failed|econn/i.test(p.error ?? "")) return "proxy_error"; if ([403, 429, 503].includes(p.status)) return "blocked"; if ([404, 410].includes(p.status)) return "report_not_found"; return "http_error"; }
async function radarBusy() { try { const x = JSON.parse(await readFile(`${process.env.ENCAR_COORDINATION_DIR ?? "/tmp/encar-coordination"}/radar-priority.json`, "utf8")) as { pid?: number }; process.kill(Number(x.pid), 0); return true; } catch { return false; } }
async function main() { const { data: rows, error } = await db.rpc("claim_next_encar_enrichment_queue", { p_limit: batch, p_lease_minutes: 30 }); if (error) throw new Error(error.message); const results: unknown[] = []; const claimed = (rows ?? []) as Row[]; for (const [index, row] of claimed.entries()) { if (await radarBusy()) { const remaining = claimed.slice(index).map((item) => item.id); if (remaining.length) { const released = await db.from("encar_enrichment_queue").update({ status: "queued", lease_until: null, updated_at: new Date().toISOString() }).in("id", remaining); if (released.error) throw new Error(released.error.message); } break; } const id = idOf(row); const task = row.task ?? {}; const payload: Record<string, unknown> = { encarId: id, fetchedAt: new Date().toISOString() }; const normalized: Record<string, unknown> = {}; const probes: Record<string, Probe> = {}; if (task.insurance) { probes.inspection = await get(`https://api.encar.com/v1/readside/inspection/vehicle/${id}`); probes.summary = await get(`https://api.encar.com/v1/readside/inspection/vehicle/${id}/summary`); payload.inspection = probes.inspection.body ?? null; payload.inspectionSummary = probes.summary.body ?? null; normalized.reportStatus = classification(probes.inspection); } if (task.options) { probes.options = await get(`https://api.encar.com/v1/readside/vehicles/car/${id}/options/choice`); payload.choiceOptions = probes.options.body ?? null; } if (task.gallery) { probes.detail = await get(`https://api.encar.com/v1/readside/vehicle/${id}`); payload.detail = probes.detail.body ?? null; } const classes = Object.fromEntries(Object.entries(probes).map(([k, p]) => [k, { status: p.status, classification: classification(p), error: p.error ?? null }])); const terminal = Object.values(probes).some((p) => [404, 410].includes(p.status)); const technical = Object.values(probes).some((p) => p.status === 0 || [403, 429, 503].includes(p.status)); const status = terminal && !Object.values(probes).some((p) => p.status >= 200 && p.status < 300) ? "unavailable" : technical && !Object.values(probes).some((p) => p.status >= 200 && p.status < 300) ? "failed" : "succeeded"; if (process.env.ENCAR_UNIVERSAL_DRY_RUN !== "true") { const done = await db.rpc("complete_encar_enrichment_queue_item", { p_queue_id: row.id, p_status: status, p_result: { encarId: id, blocks: task, probes: classes }, p_raw_payload: payload, p_normalized: { ...normalized, probes: classes }, p_error: status === "failed" ? JSON.stringify(classes) : null }); if (done.error) throw new Error(done.error.message); } results.push({ sourceListingId: row.source_listing_id, status, probes: classes }); await sleep(delay); } console.log(JSON.stringify({ batch, dryRun: process.env.ENCAR_UNIVERSAL_DRY_RUN === "true", claimed: claimed.length, processed: results.length, results: results.length <= 10 ? results : undefined }, null, 2)); await agent.close(); }
main().catch((e) => { console.error(e instanceof Error ? e.message : e); process.exit(1); });
